# Generated by Django 3.0.3 on 2020-06-14 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_auto_20200614_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverified',
            name='unique_number',
            field=models.PositiveIntegerField(default=881112, editable=False, unique=True),
        ),
    ]
