# Generated by Django 3.0.3 on 2020-06-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_auto_20200614_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='emailverified',
            name='unique_number',
            field=models.PositiveIntegerField(default=0, unique=True),
        ),
    ]
